VolleyManagement.UI/Areas/Mvc/ViewModels/GameResults/GameDeleteResultViewModel.cs
namespace VolleyManagement.UI.Areas.Mvc.ViewModels.GameResults
{
    /// <summary>
    /// Represents the information which will use the game delete dialog
    /// </summary>
    public class GameDeleteResultViewModel
    {
        /// <summary>
        /// Gets or sets message to user
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether gets or sets the result of delete
        /// </summary>
        public bool HasDeleted { get; set; }
    }
}

VolleyManagement.UI/Areas/Mvc/ViewModels/GameResults/GameResultViewModel.cs
namespace VolleyManagement.UI.Areas.Mvc.ViewModels.GameResults
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Contracts.Authorization;
    using Domain;
    using Domain.GamesAggregate;

    /// <summary>
    /// Represents a view model for game result.
    /// </summary>
    public class GameResultViewModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GameResultViewModel"/> class.
        /// </summary>
        public GameResultViewModel()
        {
            GameScore = new ScoreViewModel();
            SetScores = Enumerable.Repeat(new ScoreViewModel(), Constants.GameResult.MAX_SETS_COUNT).ToList();
        }

        /// <summary>
        /// Gets or sets the identifier of game result.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the tournament where game result belongs.
        /// </summary>
        public int TournamentId { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the home team which played the game.
        /// </summary>
        public int? HomeTeamId { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the away team which played the game.
        /// </summary>
        public int? AwayTeamId { get; set; }

        /// <summary>
        /// Gets or sets the name of the home team which played the game.
        /// </summary>
        public string HomeTeamName { get; set; }

        /// <summary>
        /// Gets or sets the name of the away team which played the game.
        /// </summary>
        public string AwayTeamName { get; set; }

        /// <summary>
        /// Gets or sets the final score of the game.
        /// </summary>
        public ScoreViewModel GameScore { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the technical defeat has taken place.
        /// </summary>
        public bool IsTechnicalDefeat { get; set; }

        /// <summary>
        /// Gets or sets the set scores.
        /// </summary>
        public List<ScoreViewModel> SetScores { get; set; }

        /// <summary>
        /// Gets or sets the date and time of the game.
        /// </summary>
        public DateTime? GameDate { get; set; }

        /// <summary>
        /// Gets or sets the round of the game in the tournament.
        /// </summary>
        public int Round { get; set; }

        /// <summary>
        /// Gets or sets the number of the game in the tournament
        /// </summary>
        public byte GameNumber { get; set; }

        public bool HasPenalty { get; set; }

        public bool IsHomeTeamPenalty { get; set; }

        public byte PenaltyAmount { get; set; }

        public string PenaltyDescrition { get; set; }

        /// <summary>
        /// Gets or sets a url to game video
        /// </summary>
        public string UrlToGameVideo { get; set; }


        /// <summary>
        /// Gets or sets a value indicating whether gets or sets whether it is allowed to edit game's result (for Playoff scheme)
        /// </summary>
        public bool AllowEditResult { get; set; }

        /// <summary>
        /// Gets a value indicating whether gets an identifier whether this game is a first round game.
        /// </summary>
        public bool IsFirstRoundGame
        {
            get
            {
                return Round == 1;
            }
        }

        /// <summary>
        /// Gets the format of game date
        /// </summary>
        public string ShortGameDate
        {
            get
            {
                return GameDate.HasValue ? GameDate.Value.ToString("d MMM dddd H:mm") : string.Empty;
            }
        }

        /// <summary>
        /// Gets or sets instance of <see cref="AllowedOperations"/> create object
        /// </summary>
        public AllowedOperations AllowedOperations { get; set; }

        /// <summary>
        /// Maps domain model of game result to view model of game result.
        /// </summary>
        /// <param name="gameResult">Domain model of game result.</param>
        /// <returns>View model of game result.</returns>
        public static GameResultViewModel Map(GameResultDto gameResult)
        {
            var result = new GameResultViewModel
            {
                Id = gameResult.Id,
                TournamentId = gameResult.TournamentId,
                HomeTeamId = gameResult.HomeTeamId,
                AwayTeamId = gameResult.AwayTeamId,
                HomeTeamName = gameResult.HomeTeamName,
                AwayTeamName = gameResult.AwayTeamName,
                GameDate = gameResult.GameDate,
                GameNumber = gameResult.GameNumber,
                Round = gameResult.Round,
                UrlToGameVideo = gameResult.UrlToGameVideo,
                GameScore = new ScoreViewModel { Home = gameResult.Result.GameScore.Home, Away = gameResult.Result.GameScore.Away },
                IsTechnicalDefeat = gameResult.Result.GameScore.IsTechnicalDefeat,
                AllowEditResult = gameResult.AllowEditResult,
                SetScores = gameResult.Result.SetScores.Select(item => new ScoreViewModel
                {
                    Home = item.Home,
                    Away = item.Away,
                    IsTechnicalDefeat = item.IsTechnicalDefeat
                }).ToList()
            };

            if (gameResult.HasResult && gameResult.Result.Penalty != null)
            {
                var penalty = gameResult.Result.Penalty;
                result.HasPenalty = true;
                result.IsHomeTeamPenalty = penalty.IsHomeTeam;
                result.PenaltyAmount = penalty.Amount;
                result.PenaltyDescrition = penalty.Description;
            }

            return result;
        }

        /// <summary>
        /// Maps view model of game result to domain model of game.
        /// </summary>
        /// <returns>Domain model of game.</returns>
        public Game ToDomain()
        {
            var penalty = MapPenalty();
            var gameScore = GameScore.ToDomain();
            gameScore.IsTechnicalDefeat = IsTechnicalDefeat;
            return new Game
            {
                Id = Id,
                TournamentId = TournamentId,
                HomeTeamId = HomeTeamId,
                AwayTeamId = AwayTeamId,
                Round = Convert.ToByte(Round),
                GameDate = GameDate,
                GameNumber = GameNumber,
                Result = new Result
                {
                    GameScore = gameScore,
                    SetScores = SetScores.Select(item => item.ToDomain()).ToList(),
                    Penalty = penalty
                },
                UrlToGameVideo = UrlToGameVideo
            };
        }

        private Penalty MapPenalty()
        {
            Penalty result = null;

            if (HasPenalty)
            {
                result = new Penalty
                {
                    IsHomeTeam = IsHomeTeamPenalty,
                    Amount = PenaltyAmount,
                    Description = PenaltyDescrition
                };
            }

            return result;
        }
    }
}

VolleyManagement.UI/Areas/Mvc/ViewModels/GameResults/ScoreViewModel.cs
namespace VolleyManagement.UI.Areas.Mvc.ViewModels.GameResults
{
    using VolleyManagement.Domain.GamesAggregate;

    public class ScoreViewModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreViewModel"/> class that contains default score.
        /// </summary>
        public ScoreViewModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreViewModel"/> class that contains specified score.
        /// </summary>
        /// <param name="home">Score of the home team.</param>
        /// <param name="away">Score of the away team.</param>
        /// <param name="isTechnicalDefeat">Indicating whether the technical defeat has taken place.</param>
        public ScoreViewModel(byte home, byte away, bool isTechnicalDefeat = false)
        {
            Home = home;
            Away = away;
            IsTechnicalDefeat = isTechnicalDefeat;
        }

        /// <summary>
        /// Gets or sets the score of the home team.
        /// </summary>
        public byte Home { get; set; }

        /// <summary>
        /// Gets or sets the score of the away team.
        /// </summary>
        public byte Away { get; set; }

        /// <summary>
        /// Gets a value indicating whether gets an indicator whether score is empty.
        /// </summary>
        /// <returns>True if score is empty; otherwise, false.</returns>
        public bool IsEmpty
        {
            get
            {
                return Home == 0 && Away == 0;
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether the technical defeat has taken place.
        /// </summary>
        public bool IsTechnicalDefeat { get; set; }

        /// <summary>
        /// Gets formatted game score
        /// </summary>
        public string GetFormattedScore
        {
            get
            {
                return IsTechnicalDefeat ? $"{Home}:{Away}*" : $"{Home}:{Away}";
            }
        }

        /// <summary>
        /// Maps view model of score to domain model of game.
        /// </summary>
        /// <returns>Domain model of game.</returns>
        public Score ToDomain()
        {
            return new Score
            {
                Home = Home,
                Away = Away,
                IsTechnicalDefeat = IsTechnicalDefeat
            };
        }
    }
}

VolleyManagement.UI/Areas/Mvc/Controllers/Domain/GameResultsController.cs
namespace VolleyManagement.UI.Areas.Mvc.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Contracts;
    using Contracts.Authorization;
    using Contracts.Exceptions;
    using Domain.RolesAggregate;
    using ViewModels.GameResults;

    /// <summary>
    /// Represents a controller that contains game results actions.
    /// </summary>
    public class GameResultsController : Controller
    {
        private readonly IGameService _gameService;
        private readonly ITeamService _teamService;
        private readonly IAuthorizationService _authService;

        /// <summary>
        /// Initializes a new instance of the <see cref="GameResultsController"/> class.
        /// </summary>
        /// <param name="gameResultService">Instance of a class which implements <see cref="IGameResultService"/>.</param>
        /// <param name="teamService">Instance of a class which implements <see cref="ITeamService"/>.</param>
        /// <param name="authService">The authorization service</param>
        public GameResultsController(IGameService gameResultService, ITeamService teamService, IAuthorizationService authService)
        {
            _gameService = gameResultService;
            _teamService = teamService;
            _authService = authService;
        }

        /// <summary>
        /// Renders a view with game results of the specified tournament.
        /// </summary>
        /// <param name="tournamentId">Identifier of the tournament.</param>
        /// <param name="tournamentName">Name of the tournament.</param>
        /// <returns>View with game results of the specified tournament.</returns>
        public ActionResult TournamentResults(int tournamentId, string tournamentName)
        {
            var tournamentResults = new TournamentResultsViewModel
            {
                Id = tournamentId,
                Name = tournamentName,
                GameResults = _gameService.GetTournamentResults(tournamentId).Select(gr => GameResultViewModel.Map(gr)).ToList(),
                Authorization = _authService.GetAllowedOperations(new List<AuthOperation>
                {
                AuthOperations.Games.EditResult,
                AuthOperations.Games.Delete
                })
            };

            return View(tournamentResults);
        }

        /// <summary>
        /// Renders a view with empty fields of game result for create operation.
        /// </summary>
        /// <param name="tournamentId">Identifier of the tournament where game result belongs.</param>
        /// <returns>View with empty fields of game result.</returns>
        public ActionResult Create(int tournamentId)
        {
            var gameResultViewModel = new GameResultViewModel
            {
                TournamentId = tournamentId,
            };

            return View(gameResultViewModel);
        }

        /// <summary>
        /// Creates a new game result if fields data is valid and redirects to the specified page.
        /// </summary>
        /// <param name="gameResultViewModel">View model of game result.</param>
        /// <returns>View with empty fields of game result if fields data is not valid;
        /// otherwise, view of the specified page.</returns>
        [HttpPost]
        public ActionResult Create(GameResultViewModel gameResultViewModel)
        {
            var gameResult = gameResultViewModel.ToDomain();

            try
            {
                _gameService.Create(gameResult);
                return RedirectToAction("Details", "Tournaments", new { id = gameResultViewModel.TournamentId });
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError("ValidationMessage", ex.Message);
                return View(gameResultViewModel);
            }
        }

        /// <summary>
        /// Renders a view with filled in fields of game result for edit operation.
        /// </summary>
        /// <param name="id">Identifier of the game result.</param>
        /// <returns>View with filled in fields of game result.</returns>
        public ActionResult Edit(int id)
        {
            var gameResult = _gameService.Get(id);

            if (gameResult == null)
            {
                return HttpNotFound();
            }

            var gameResultsViewModel = GameResultViewModel.Map(gameResult);
            return View(gameResultsViewModel);
        }

        /// <summary>
        /// Edit an existing game result if fields data is valid and redirects to the specified page.
        /// </summary>
        /// <param name="gameResultViewModel">View model of game result.</param>
        /// <returns>View with filled in fields of game result if fields data is not valid;
        /// otherwise, view of the specified page.</returns>
        [HttpPost]
        public ActionResult Edit(GameResultViewModel gameResultViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var gameResult = gameResultViewModel.ToDomain();
                    _gameService.EditGameResult(gameResult);
                    return RedirectToAction("ShowSchedule", "Tournaments", new { tournamentId = gameResultViewModel.TournamentId });
                }
            }
            catch (MissingEntityException)
            {
                ModelState.AddModelError(string.Empty, Resources.UI.GameResultsController.GameResultWasDeleted);
            }
            catch (ArgumentException)
            {
                ModelState.AddModelError(string.Empty, Resources.UI.GameResultsController.GameResultNotEdited);
            }

            return View(gameResultViewModel);
        }

        /// <summary>
        /// Deletes an existing game result by its identifier.
        /// </summary>
        /// <param name="id">Identifier of the game result.</param>
        /// <returns>Result message</returns>
        public JsonResult Delete(int id)
        {
            try
            {
                _gameService.Delete(id);
            }
            catch (ArgumentNullException ex)
            {
                return Json(new GameDeleteResultViewModel { Message = ex.Message, HasDeleted = false });
            }
            catch (ArgumentException ex)
            {
                return Json(new GameDeleteResultViewModel { Message = ex.Message, HasDeleted = false });
            }

            return Json(new GameDeleteResultViewModel
            {
                Message = Resources.UI.GameResultsController.GameWasDeletedSuccessfully,
                HasDeleted = true
            });
        }
    }
}

VolleyManagement.UI/Areas/Mvc/Views/GameResults/Create.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.GameResults.GameResultViewModel

@{
    ViewBag.Title = Resources.UI.GameResultViews.CreateTitle;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "GameResults", FormMethod.Post, new { id = "createForm", name = "createForm" }))
{
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Partial("_CreateOrEdit", Model)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="@Resources.UI.GameResultViews.Create" class="btn btn-default" />
        </div>
    </div>

}

<script src="~/Scripts/GameResults/ResultsValidate.js" type="text/javascript"></script>

VolleyManagement.UI/Areas/Mvc/Views/GameResults/Edit.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.GameResults.GameResultViewModel

@{
    ViewBag.Title = Resources.UI.GameResultViews.EditTitle;
}

<h2>@Resources.UI.GameResultViews.EditTitle</h2>

@using (Html.BeginForm("Edit", "GameResults", FormMethod.Post, new { id = "createForm", name = "createForm" }))
{
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Partial("_CreateOrEdit", Model)

    @Html.HiddenFor(model => model.GameNumber);
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="@Resources.UI.GameResultViews.Save" class="btn btn-default" />
            @Html.ActionLink(@Resources.UI.GameResultViews.Back, 
                "ShowSchedule",
                "Tournaments",
                new { tournamentId = Model.TournamentId }, 
                new { @class = "btn btn-default", @id = "backToSchedule" })
        </div>
    </div>

}

<script src="~/Scripts/GameResults/ResultsValidate.js" type="text/javascript"></script>

VolleyManagement.UI/Areas/Mvc/Views/GameResults/TournamentResults.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.GameResults.TournamentResultsViewModel
@using VolleyManagement.Domain.RolesAggregate

<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = Resources.UI.GameResultViews.TournamentResultsTitle;
}

<h2>@ViewBag.Title</h2>

<fieldset>
    @{
        string legendText = string.Format(Resources.UI.GameResultViews.TournamentResultsLegend, Model.Name);
        string setsScoreText = string.Empty;
        string set1ScoreText = string.Empty;
        string set2ScoreText = string.Empty;
        string set3ScoreText = string.Empty;
        string set4ScoreText = string.Empty;
        string set5ScoreText = string.Empty;
        int number = 0;
    }

    <legend>@legendText</legend>
    @if (Model.GameResults.Count == 0)
    {
        <p>@Resources.UI.GameResultViews.NoGameResults</p>
    }
    else
    {
        <table class="results">
            <thead>
                <tr class="results-header-row">
                    <th class="results-header-cell">@Resources.UI.GameResultViews.ResultNumberHeader</th>
                    <th class="results-header-cell">@Resources.UI.GameResultViews.GameResultHeader</th>
                    <th class="results-header-cell">@Resources.UI.GameResultViews.Set1ScoreHeader</th>
                    <th class="results-header-cell">@Resources.UI.GameResultViews.Set2ScoreHeader</th>
                    <th class="results-header-cell">@Resources.UI.GameResultViews.Set3ScoreHeader</th>
                    <th class="results-header-cell">@Resources.UI.GameResultViews.Set4ScoreHeader</th>
                    <th class="results-header-cell">@Resources.UI.GameResultViews.Set5ScoreHeader</th>
                    <th class="results-operation-header-cell"></th>
                    <th class="results-operation-header-cell"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var gameResult in Model.GameResults)
                {
                    setsScoreText = gameResult.IsTechnicalDefeat
                        ? gameResult.GameScore.Home > gameResult.GameScore.Away
                            ? string.Format("{0}*:{1}", gameResult.GameScore.Home, gameResult.GameScore.Away)
                            : string.Format("{0}:{1}*", gameResult.GameScore.Home, gameResult.GameScore.Away)
                        : string.Format("{0}:{1}", gameResult.GameScore.Home, gameResult.GameScore.Away);

                    set1ScoreText = string.Format("{0}:{1}", gameResult.SetScores[0].Home, gameResult.SetScores[0].Away);
                    set2ScoreText = string.Format("{0}:{1}", gameResult.SetScores[1].Home, gameResult.SetScores[1].Away);
                    set3ScoreText = string.Format("{0}:{1}", gameResult.SetScores[2].Home, gameResult.SetScores[2].Away);
                    set4ScoreText = string.Format("{0}:{1}", gameResult.SetScores[3].Home, gameResult.SetScores[3].Away);
                    set5ScoreText = string.Format("{0}:{1}", gameResult.SetScores[4].Home, gameResult.SetScores[4].Away);

                    <tr class="results-row">
                        <td class="results-cell">@(++number)</td>
                        <td class="results-cell game-score-cell">
                            <div class="game-home-team">@gameResult.HomeTeamName</div>
                            <div class="game-score">@setsScoreText</div>
                            <div class="game-away-team">@gameResult.AwayTeamName</div>
                        </td>
                        <td class="results-cell">@set1ScoreText</td>
                        <td class="results-cell">@set2ScoreText</td>
                        <td class="results-cell">@set3ScoreText</td>
                        <td class="results-cell">@set4ScoreText</td>
                        <td class="results-cell">@set5ScoreText</td>
                        <td class="results-first-operation-cell">
                            @if (Model.Authorization.IsAllowed(AuthOperations.Games.EditResult))
                            {
                                @Html.ActionLink(Resources.UI.GameResultViews.Edit, "Edit", new { id = gameResult.Id }, null)
                            }
                        </td>
                        <td></td>
                    </tr>
                }
            </tbody>
        </table>
    }
</fieldset>

<p>@Html.ActionLink(Resources.UI.GameResultViews.BackToTournament, "Details", "Tournaments", new { id = Model.Id }, null)</p>

<script>
    var DELETE_CONFIRMATION_MESSAGE = "@Resources.UI.GameResultViews.DeleteConfirmationText";
    var DELETE_FAILED_MESSAGE = "@Resources.UI.GameResultsController.GameResultNotFoundView";
</script>

VolleyManagement.UI/Areas/Mvc/Views/GameResults/_CreateOrEdit.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.GameResults.GameResultViewModel

@using GameResultConstants = VolleyManagement.Domain.Constants.GameResult;
@using DomainResources = VolleyManagement.Domain.Properties.Resources;

@Html.ValidationMessage("ValidationMessage", new { @class = "text-danger", name = "ValidationMessage" })
@Html.HiddenFor(model => model.TournamentId)

<div class="form-group">
    @Resources.UI.GameResultViews.TeamsFields

    @Html.LabelFor(model => model.HomeTeamName, Model.HomeTeamName)
    @Html.LabelFor(model => model.AwayTeamName, Model.AwayTeamName)

    @Html.DisplayFor(model => model.ShortGameDate)
    @Html.HiddenFor(model => model.HomeTeamId)
    @Html.HiddenFor(model => model.AwayTeamId)
    @Html.HiddenFor(model => model.GameDate)
    @Html.HiddenFor(model => model.Round)
</div>

<div class="form-group">
    @Resources.UI.GameResultViews.SetsScoreFields
    @Html.EditorFor(model => model.GameScore.Home, new { htmlAttributes = new { @class = "form-control" } })

    @Html.EditorFor(model => model.GameScore.Away, new { htmlAttributes = new { @class = "form-control" } })
</div>

<div class="form-group">
    <label for="@Model.IsTechnicalDefeat">
        @Resources.UI.GameResultViews.TechnicalDefeatField
        @Html.EditorFor(model => model.IsTechnicalDefeat)
        @Html.ValidationMessageFor(model => model.IsTechnicalDefeat, "", new { @class = "text-danger" })
    </label>
</div>

<div class="form-group">
    <label for="@Model.HasPenalty">
        Penalty
        @Html.EditorFor(model => model.HasPenalty)
        @Html.ValidationMessageFor(model => model.HasPenalty, "", new { @class = "text-danger" })
    </label>
    <div>
        <span>
            First Team? @Html.EditorFor(m => m.IsHomeTeamPenalty)
        </span>
        <span>
            Amount @Html.EditorFor(m => m.PenaltyAmount)
        </span>
        <span>
            Reason @Html.EditorFor(m => m.PenaltyDescrition)
        </span>
    </div>
</div>

@for (int i = 0; i < Model.SetScores.Count; i++)
{
    <div class="form-group">
        @string.Format(Resources.UI.GameResultViews.SetFields, i + 1)
        @Html.EditorFor(model => model.SetScores[i].Home, new { htmlAttributes = new { @class = "form-control" } })

        @Html.EditorFor(model => model.SetScores[i].Away, new { htmlAttributes = new { @class = "form-control" } })
        @Resources.UI.GameResultViews.SetTechnicalDefeat @Html.CheckBoxFor(model => model.SetScores[i].IsTechnicalDefeat, new { htmlAttributes = new { @class = "form-control" } })
    </div>
}

<div class="form-group">
    @Html.LabelFor(model => model.UrlToGameVideo, @Resources.UI.GameResultViews.UrlToGameVideo)
    @Html.EditorFor(model => model.UrlToGameVideo, new { htmlAttributes = new { @class = "form-control",  style="display: inline-block; width: 84%;" } })
</div>


<script>

    @{
        <text>
    var gameResultConstants = {
        "SETS_COUNT_TO_WIN": @GameResultConstants.SETS_COUNT_TO_WIN,
        "SET_POINTS_MIN_DELTA_TO_WIN": @GameResultConstants.SET_POINTS_MIN_DELTA_TO_WIN,
        "SET_POINTS_MIN_VALUE_TO_WIN": @GameResultConstants.SET_POINTS_MIN_VALUE_TO_WIN,
        "FIFTH_SET_POINTS_MIN_VALUE_TO_WIN": @GameResultConstants.FIFTH_SET_POINTS_MIN_VALUE_TO_WIN,
        "TECHNICAL_DEFEAT_SETS_WINNER_SCORE": @GameResultConstants.TECHNICAL_DEFEAT_SETS_WINNER_SCORE,
        "TECHNICAL_DEFEAT_SETS_LOSER_SCORE": @GameResultConstants.TECHNICAL_DEFEAT_SETS_LOSER_SCORE,
        "TECHNICAL_DEFEAT_SET_WINNER_SCORE":@GameResultConstants.TECHNICAL_DEFEAT_SET_WINNER_SCORE,
        "TECHNICAL_DEFEAT_SET_LOSER_SCORE":@GameResultConstants.TECHNICAL_DEFEAT_SET_LOSER_SCORE,
        "UNPLAYED_SET_HOME_SCORE": @GameResultConstants.UNPLAYED_SET_HOME_SCORE,
        "UNPLAYED_SET_AWAY_SCORE": @GameResultConstants.UNPLAYED_SET_AWAY_SCORE,
        "MAX_SETS_COUNT": @GameResultConstants.MAX_SETS_COUNT
        };

    var resourceMessages = {
        "GameResultSameTeam": "@DomainResources.GameResultSameTeam",
        "GameResultSetsScoreInvalid": "@DomainResources.GameResultSetsScoreInvalid",
        "GameResultSetsScoreNoMatchSetScores": "@DomainResources.GameResultSetsScoreNoMatchSetScores",
        "GameResultRequiredSetScores": "@DomainResources.GameResultRequiredSetScores",
        "GameResultOptionalSetScores": "@DomainResources.GameResultOptionalSetScores",
        "GameResultPreviousOptionalSetUnplayed": "@DomainResources.GameResultPreviousOptionalSetUnplayed",
        "GameResultSetScoresNotOrdered": "@DomainResources.GameResultSetScoresNotOrdered",
        "GameResultFifthSetScoreInvalid":"@DomainResources.GameResultFifthSetScoreInvalid"
    };
    </text>
    }

</script>