VolleyManagement.UI/Areas/Mvc/ViewModels/Tournaments/DivisionScheduleViewModel.cs
namespace VolleyManagement.UI.Areas.Mvc.ViewModels.Tournaments
{
    public class DivisionScheduleViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int NumberOfRounds { get; set; }
    }
}

VolleyManagement.UI/Areas/Mvc/ViewModels/Tournaments/DivisionViewModel.cs
namespace VolleyManagement.UI.Areas.Mvc.ViewModels.Division
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Domain;
    using Domain.TournamentsAggregate;
    using Resources.UI;

    /// <summary>
    /// Represents division's view model.
    /// </summary>
    public class DivisionViewModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DivisionViewModel"/> class.
        /// </summary>
        public DivisionViewModel()
        {
            Name = string.Format(
                "{0} {1}",
                ViewModelResources.DivisionDefaultName,
                Constants.Division.MIN_DIVISIONS_COUNT);
            Groups = new List<GroupViewModel>();
            IsEmpty = true;
        }

        /// <summary>
        /// Gets or sets the division's identifier.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the division's name.
        /// </summary>
        [Display(Name = "DivisionName", ResourceType = typeof(ViewModelResources))]
        [Required(
            ErrorMessageResourceName = "DivisionNameRequired",
            ErrorMessageResourceType = typeof(ViewModelResources))]
        [MaxLength(
            Constants.Division.MAX_NAME_LENGTH,
            ErrorMessageResourceName = "DivisionNameMaxLengthErrorMessage",
            ErrorMessageResourceType = typeof(ViewModelResources))]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the tournament that contains the division.
        /// </summary>
        public int TournamentId { get; set; }

        /// <summary>
        /// Gets or sets list of groups
        /// </summary>
        [Display(Name = "Groups", ResourceType = typeof(ViewModelResources))]
        public List<GroupViewModel> Groups { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether division is empty.
        /// </summary>
        public bool IsEmpty { get; set; }

        /// <summary>
        /// Gets a value indicating whether count groups is min.
        /// </summary>
        public bool IsGroupsCountMin
        {
            get { return Groups.Count == Constants.Group.MIN_GROUPS_COUNT; }
        }

        /// <summary>
        /// Gets a value indicating whether count of groups is max.
        /// </summary>
        public bool IsGroupsCountMax
        {
            get { return Groups.Count == Constants.Group.MAX_GROUPS_COUNT; }
        }
        #region Factory methods

        /// <summary>
        /// Maps domain model of <see cref="Division"/> to view model of <see cref="Division"/>.
        /// Maps view model of <see cref="Division"/> to domain model of <see cref="Division"/>.
        /// </summary>
        /// <param name="division">Domain model of <see cref="Division"/>.</param>
        /// <returns>View model of <see cref="Division"/>.</returns>
        public static DivisionViewModel Map(Division division)
        {
            var divisionViewModel = new DivisionViewModel()
            {
                Id = division.Id,
                Name = division.Name,
                IsEmpty = division.IsEmpty
            };

            divisionViewModel.Groups = division.Groups.Select(g => GroupViewModel.Map(g)).ToList();
            return divisionViewModel;
        }

        /// <summary>
        /// Maps view model of <see cref="Division"/> to domain model of <see cref="Division"/>.
        /// </summary>
        /// <returns>Domain model of <see cref="Division"/>.</returns>
        public Division ToDomain()
        {
            var division = new Division()
            {
                Id = Id,
                Name = Name,
                TournamentId = TournamentId
            };

            division.Groups = Groups.Select(g => g.ToDomain()).ToList();
            return division;
        }

        #endregion
    }
}

VolleyManagement.UI/Areas/Mvc/Controllers/Domain/TournamentsController.cs
namespace VolleyManagement.UI.Areas.Mvc.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Contracts;
    using Contracts.Authorization;
    using Contracts.Exceptions;
    using Crosscutting.Contracts.Providers;
    using Domain.RolesAggregate;
    using Domain.TeamsAggregate;
    using Domain.TournamentRequestAggregate;
    using Domain.TournamentsAggregate;
    using Resources.UI;
    using ViewModels.Division;
    using ViewModels.GameResults;
    using ViewModels.Teams;
    using ViewModels.Tournaments;

    /// <summary>
    /// Defines TournamentsController
    /// </summary>
    public class TournamentsController : Controller
    {
        private const int ANONYM = -1;
        private const int DAYS_TO_APPLYING_PERIOD_START = 14;
        private const int DAYS_FOR_APPLYING_PERIOD = 14;
        private const int DAYS_FROM_APPLYING_PERIOD_END_TO_GAMES_START = 7;
        private const int DAYS_FOR_GAMES_PERIOD = 120;
        private const int DAYS_FROM_GAMES_START_TO_TRANSFER_START = 1;
        private const int DAYS_FOR_TRANSFER_PERIOD = 21;
        private const int MIN_ROUND_NUMBER = 1;

        /// <summary>
        /// Holds TournamentService instance
        /// </summary>
        private readonly ITournamentService _tournamentService;

        /// <summary>
        /// Holds AuthorizationService instance
        /// </summary>
        private readonly IAuthorizationService _authService;

        /// <summary>
        /// Holds GameService instance
        /// </summary>
        private readonly IGameService _gameService;

        private readonly ITournamentRequestService _requestService;

        private readonly ICurrentUserService _currentUserService;

        /// <summary>
        /// Initializes a new instance of the <see cref="TournamentsController"/> class
        /// </summary>
        /// <param name="tournamentService">The tournament service</param>
        /// <param name="gameService">The game service</param>
        /// <param name="authService">The authorization service</param>
        /// <param name="requestService">The request service</param>
        /// <param name="currentUserService">The current user service</param>
        public TournamentsController(
            ITournamentService tournamentService,
            IGameService gameService,
            IAuthorizationService authService,
            ITournamentRequestService requestService,
            ICurrentUserService currentUserService)
        {
            _tournamentService = tournamentService;
            _gameService = gameService;
            _requestService = requestService;
            _currentUserService = currentUserService;
            _authService = authService;
        }

        /// <summary>
        /// Gets current and upcoming tournaments from TournamentService
        /// </summary>
        /// <returns>View with collection of tournaments</returns>
        public ActionResult Index()
        {
            var tournamentsCollections = new TournamentsCollectionsViewModel
            {
                Authorization = _authService.GetAllowedOperations(AuthOperations.Tournaments.Create)
            };

            var actualTournaments = _tournamentService.GetActual().ToArray();

            tournamentsCollections.CurrentTournaments = actualTournaments
                .Where(tr => tr.State == TournamentStateEnum.Current);

            tournamentsCollections.UpcomingTournaments = actualTournaments
                .Where(tr => tr.State == TournamentStateEnum.Upcoming);

            return View(tournamentsCollections);
        }

        /// <summary>
        /// Gets archived tournaments from TournamentService
        /// </summary>
        /// <returns>View with collection of archived tournaments</returns>
        public ActionResult Archived()
        {
            List<Tournament> archivedTournaments = _tournamentService.GetArchived().ToList();

            return View(archivedTournaments);
        }

        /// <summary>
        /// Get finished tournaments
        /// </summary>
        /// <returns>Json result</returns>
        public JsonResult GetFinished()
        {
            var result = _tournamentService.GetFinished().ToList()
                 .Select(t => TournamentViewModel.Map(t));
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Archive current Tournament
        /// </summary>
        /// <param name="tournamentId">Tournament id</param>
        /// <returns>Index View of Tournament</returns>
        [HttpPost]
        public ActionResult Archive(int tournamentId)
        {
            _tournamentService.Archive(tournamentId);
            return new EmptyResult();
        }

        /// <summary>
        /// Gets details for specific tournament
        /// </summary>
        /// <param name="id">Tournament id</param>
        /// <returns>View with specific tournament</returns>
        public ActionResult Details(int id)
        {
            var tournament = _tournamentService.Get(id);

            if (tournament == null)
            {
                return HttpNotFound();
            }

            var tournamentViewModel = TournamentViewModel.Map(tournament);
            tournamentViewModel.Authorization = _authService.GetAllowedOperations(new List<AuthOperation>
            {
                AuthOperations.Tournaments.Edit,
                AuthOperations.Tournaments.ManageTeams,
                AuthOperations.Tournaments.Archive
            });

            return View(tournamentViewModel);
        }

        /// <summary>
        /// Create tournament action (GET)
        /// </summary>
        /// <returns>View to create a tournament</returns>
        public ActionResult Create()
        {
            var now = TimeProvider.Current.DateTimeNow;

            var tournamentViewModel = new TournamentViewModel()
            {
                Season = (short)now.Year,
                ApplyingPeriodStart = now.AddDays(DAYS_TO_APPLYING_PERIOD_START),
                ApplyingPeriodEnd = now.AddDays(DAYS_TO_APPLYING_PERIOD_START
                                              + DAYS_FOR_APPLYING_PERIOD),
                GamesStart = now.AddDays(DAYS_TO_APPLYING_PERIOD_START
                                               + DAYS_FOR_APPLYING_PERIOD
                                               + DAYS_FROM_APPLYING_PERIOD_END_TO_GAMES_START),
                GamesEnd = now.AddDays(DAYS_TO_APPLYING_PERIOD_START
                                     + DAYS_FOR_APPLYING_PERIOD
                                     + DAYS_FROM_APPLYING_PERIOD_END_TO_GAMES_START
                                     + DAYS_FOR_GAMES_PERIOD),
                TransferStart = now.AddDays(DAYS_TO_APPLYING_PERIOD_START
                                          + DAYS_FOR_APPLYING_PERIOD
                                          + DAYS_FROM_APPLYING_PERIOD_END_TO_GAMES_START
                                          + DAYS_FROM_GAMES_START_TO_TRANSFER_START),
                TransferEnd = now.AddDays(DAYS_TO_APPLYING_PERIOD_START
                                        + DAYS_FOR_APPLYING_PERIOD
                                        + DAYS_FROM_APPLYING_PERIOD_END_TO_GAMES_START
                                        + DAYS_FROM_GAMES_START_TO_TRANSFER_START
                                        + DAYS_FOR_TRANSFER_PERIOD)
            };

            return View(tournamentViewModel);
        }

        /// <summary>
        /// Create tournament action (POST)
        /// </summary>
        /// <param name="tournamentViewModel">Tournament, which the user wants to create</param>
        /// <returns>Index view if tournament was valid, else - create view</returns>
        [HttpPost]
        public ActionResult Create(TournamentViewModel tournamentViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var tournament = tournamentViewModel.ToDomain();
                    _tournamentService.Create(tournament);
                    return RedirectToAction("Index");
                }

                return View(tournamentViewModel);
            }
            catch (TournamentValidationException e)
            {
                ModelState.AddModelError(e.ValidationKey, e.Message);
                return View(tournamentViewModel);
            }
        }

        /// <summary>
        /// Edit tournament action (GET)
        /// </summary>
        /// <param name="id">Tournament id</param>
        /// <returns>View to edit specific tournament</returns>
        public ActionResult Edit(int id)
        {
            return GetTournamentView(id);
        }

        /// <summary>
        /// Edit tournament action (POST)
        /// </summary>
        /// <param name="tournamentViewModel">Tournament after editing</param>
        /// <returns>Index view if tournament was valid, else - edit view</returns>
        [HttpPost]
        public ActionResult Edit(TournamentViewModel tournamentViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var tournament = tournamentViewModel.ToDomain();
                    _tournamentService.Edit(tournament);
                    return RedirectToAction("Index");
                }

                return View(tournamentViewModel);
            }
            catch (TournamentValidationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(tournamentViewModel);
            }
        }

        /// <summary>
        /// Delete tournament action (GET)
        /// </summary>
        /// <param name="id">Tournament id</param>
        /// <returns>View to delete specific tournament</returns>
        public ActionResult Delete(int id)
        {

VolleyManagement.UI/Areas/WebAPI/Controllers/TeamsController.cs
namespace VolleyManagement.UI.Areas.WebAPI.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using VolleyManagement.Contracts;
    using VolleyManagement.Contracts.Exceptions;
    using VolleyManagement.UI.Areas.WebApi.ViewModels.Players;
    using VolleyManagement.UI.Areas.WebApi.ViewModels.Teams;

    public class TeamsController : ApiController
    {
        private const string CONTROLLER_NAME = "teams";
        private readonly ITeamService _teamService;

        /// <summary>
        /// Initializes a new instance of the <see cref="TeamsController" /> class
        /// </summary>
        /// <param name="teamService"> The team service. </param>
        public TeamsController(ITeamService teamService)
        {
            _teamService = teamService;
        }

        /// <summary>
        /// Creates Team
        /// </summary>
        /// <param name="team"> The  team as ViewModel. </param>
        /// <returns> Has been saved successfully - Created OData result
        /// unsuccessfully - Bad request </returns>
        public IHttpActionResult Post(TeamViewModel team)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var teamToCreate = team.ToDomain();

            try
            {
                _teamService.Create(teamToCreate);
            }
            catch (MissingEntityException ex)
            {
                ModelState.AddModelError(string.Format("{0}.{1}", CONTROLLER_NAME, ex.Source), ex.Message);
                return BadRequest(ModelState);
            }

            team.Id = teamToCreate.Id;
            return Ok(team);
        }

        /// <summary>
        /// Gets teams.
        /// </summary>
        /// <returns>Team list. </returns>
        public IEnumerable<TeamViewModel> GetTeams()
        {
            return _teamService.Get()
                                .ToList()
                                .Select(t => TeamViewModel.Map(t));
        }

        /// <summary>
        /// Gets roster of the team.
        /// </summary>
        /// <param name="key">Id of the team.</param>
        /// <returns>Players in team roster.</returns>
        public IEnumerable<PlayerViewModel> GetPlayers(int key)
        {
            var result = _teamService
                .GetTeamRoster(key)
                .Select(p => PlayerViewModel.Map(p));

            return result;
        }

        /// <summary> Deletes team </summary>
        /// <param name="id"> The id. </param>
        /// <returns> The <see cref="IHttpActionResult"/>. </returns>
        public IHttpActionResult Delete(int id)
        {
            try
            {
                _teamService.Delete(id);
            }
            catch (MissingEntityException ex)
            {
                return BadRequest(ex.Message);
            }

            return StatusCode(HttpStatusCode.NoContent);
        }
    }
}

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/ApplyForTournament.cshtml
@using Resources.UI
@model VolleyManagement.UI.Areas.Mvc.ViewModels.Tournaments.TournamentApplyViewModel
@{
    ViewBag.Title = @Resources.UI.PlayerViews.ApplyForTournament;
}

@Html.HiddenFor(model => model.Id, new { id = "tournamentId", Value = @Model.Id })

<h2>@Resources.UI.PlayerViews.ApplyTeamFor @Model.TournamentTitle @Resources.UI.PlayerViews.Tournament</h2>
@if (Model.Teams.Count() == 0)
{
   @Resources.UI.PlayerViews.NoAvaliableTeams
}
else
{
    <table id="tournamentRoster">
        <tr>
            <td id="team">
                @Html.DropDownListFor(x => x.TeamId,
                        new SelectList(Model.Teams, "Id", "Name"))
            </td>
        </tr>
    </table>

    <p>
        <input type="checkbox" name="agree" id="agree">@Resources.UI.PlayerViews.IAccept<a href="License">@Resources.UI.PlayerViews.TournamentRegulations</a>
    </p>

        <div>
            <button name="apply-submit" id="apply" class="btn btn-default" disabled>@Resources.UI.PlayerViews.Accept</button>
            <button id="apply-cancel" class="btn btn-default">@Resources.UI.PlayerViews.BackPrevPage</button>

            <span id="ajaxResultMessage"></span>
        </div>
}
@Scripts.Render("~/bundles/tournamentapplyscripts")

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/Archived.cshtml
@using VolleyManagement.UI.Areas.Mvc
@model IEnumerable<VolleyManagement.Domain.TournamentsAggregate.Tournament>

@{
    ViewBag.Title = Resources.UI.TournamentViews.ArchivedTournamentsIndexTitle;
}

<h2>@ViewBag.Title</h2>

<table class="table" @ViewBag.TableId>
    <thead>
        <tr>
            <td width="400">
                @Html.DisplayNameFor(model => model.Name)
            </td>
            <td width="100">
                @Html.DisplayNameFor(model => model.Season)
            </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var tournament in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(tournament.Name, "Details", new { id = tournament.Id })
                </td>
                <td>
                    @Html.DisplaySeason(tournament.Season)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = tournament.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/Create.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.Tournaments.TournamentViewModel

@{
    ViewBag.Title = Resources.UI.TournamentViews.CreateTournamentTitle;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>@Resources.UI.TournamentViews.TournamentLegend</legend>
		@Html.Partial("_CreateOrEdit", Model)
        <p>
            <input type="submit" value="@Resources.UI.TournamentViews.Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(Resources.UI.TournamentViews.BackToList, "Index")
</div>

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/Delete.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.Tournaments.TournamentViewModel
@using VolleyManagement.Crosscutting.Contracts.Extensions
@using VolleyManagement.UI.Areas.Mvc;

@{
    ViewBag.Title = Resources.UI.TournamentViews.DeleteTournamentTitle;
}

<h2>@ViewBag.Title</h2>

<h3>@Resources.UI.TournamentViews.DeleteConfirm</h3>
<fieldset>
    <legend>@Resources.UI.TournamentViews.TournamentLegend</legend>

    <div class="display-label">@Html.LabelFor(model => model.Name)</div>
    <div class="display-field">@Model.Name</div>

    <div class="display-label">@Html.LabelFor(model => model.Description)</div>
    <div class="display-field">@Html.DisplayFor(model => model.Description)</div>

    <div class="display-label">@Html.LabelFor(model => model.Season)</div>
    <div class="display-field">@Html.DisplaySeason(Model.Season)</div>

    <div class="display-label">@Html.LabelFor(model => model.Scheme)</div>
    <div class="display-field">@Model.Scheme.ToDescription()</div>

    <div class="display-label">@Html.LabelFor(model => model.RegulationsLink)</div>
    <div class="display-field">@Html.DisplayFor(model => model.RegulationsLink)</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="@Resources.UI.TournamentViews.Delete" /> |
        @Html.ActionLink(Resources.UI.TournamentViews.BackToList, "Index")
    </p>
}

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/EditScheduledGame.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.GameResults.GameViewModel

@{
    ViewBag.Title = @Resources.UI.TournamentViews.EditScheduledGameTitle;
}

<h2>@ViewBag.Title</h2>

@if (Model == null)
{
    @Html.ValidationMessage("LoadError")
}
else
{
    using (Html.BeginForm())
    {
        @Html.Partial("_ScheduleOrEditGame", Model);
        @Html.HiddenFor(model => model.Id);
            
        <input class="btn btn-default" type="submit" value="@Resources.UI.TournamentViews.Save" />
    }

    <br />
    @Html.ActionLink(@Resources.UI.TournamentViews.Cancel, "ShowSchedule", new { tournamentId = Model.TournamentId })
}

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/Index.cshtml
@using VolleyManagement.UI.Areas.Mvc.ViewModels.Tournaments;
@using VolleyManagement.Domain.RolesAggregate;
@model TournamentsCollectionsViewModel

@{
    ViewBag.Title = Resources.UI.TournamentViews.TournamentsIndexTitle;
}

<h2>@ViewBag.Title</h2>

@if (Model.Authorization.IsAllowed(AuthOperations.Tournaments.Create))
{
    <p>
        @Html.ActionLink(Resources.UI.TournamentViews.CreateNewTournament, "Create")
    </p>
}
<p>
    <h3>
        @Resources.UI.TournamentViews.CurrentTournamentsHeader
    </h3>    
    @{Html.RenderPartial("TournamentsList", Model.CurrentTournaments);}
</p>
<p>
    <h3>
        @Resources.UI.TournamentViews.UpcomingTournamentsHeader
    </h3>
    @{Html.RenderPartial("TournamentsList", Model.UpcomingTournaments);}
</p>
<p>
    @Html.ActionLink(Resources.UI.TournamentViews.FinishedTournaments, string.Empty, null, 
        new { @class = "showFinishedTournamenst"})
</p>

@{ ViewBag.TableId = "id=finished_table"; }
<p>
    <h3 id="FinishedHeader">
        @Resources.UI.TournamentViews.FinishedTournamentsHeader
    </h3>

    @{Html.RenderPartial("TournamentsList", new List<VolleyManagement.Domain.TournamentsAggregate.Tournament>());}
</p>

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/ManageTournamentTeams.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.Tournaments.TournamentTeamsListReferrerViewModel
@using Resources.UI

@{
    ViewBag.Title = "ManageTournamentTeams";
}

<h2>@TournamentViews.ManageTeams</h2>

<div>
    @Html.HiddenFor(model => model.Model.TournamentId, new { id = "TournamentId" })
    <table id="tournamentRoster" class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Model.TeamsList.FirstOrDefault().Name)</th>
            <th>@Html.DisplayNameFor(model => model.Model.TeamsList.FirstOrDefault().DivisionName)</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (var team in Model.Model.TeamsList)
        {
            <tr>
                <td>@Html.ActionLink(team.Name, "Details", "Teams", new { id = team.Id, returnUrl = Model.Referer }, null)</td>
                <td>@team.DivisionName</td>
                <td></td>
                <td><button class="deleteTeamFromTournamentButton" id="@team.Id">Delete</button></td>
            </tr>
        }                
    </table>
    <div style="margin-bottom: 30px;">
        <button id="addTeamToTournamentButton" class="btn btn-success">+ Add team </button>
    </div>
        <button id="addTeamsButton" class="btn btn-default">Save</button>
        @Html.ActionLink(@TournamentViews.Cancel, "Details", new { id = Model.Model.TournamentId }, new { @class = "btn btn-default" })

        <script type="text/javascript">
            (function () {
                "use strict";

                var currNs = VM.addNamespace("tournament.addTeams");
                currNs.deleteConfirmMessage = "@TournamentViews.DeleteTournamentTeamConfirm";
                currNs.teamIsNotSelectedMessage = "@TournamentViews.TournamentTeamIsNotSelected";
                currNs.divisionIsNotSelectedMessage = "@TournamentViews.TournamentDivisionIsNotSelected";
                currNs.groupIsNotSelectedMessage = "@TournamentViews.TournamentGroupIsNotSelected";
            })();

        </script>
    </div>
@Scripts.Render("~/bundles/tournamentteamsscripts")

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/ShowSchedule.cshtml
@model ScheduleViewModel
@using VolleyManagement.Domain.TournamentsAggregate;
@using VolleyManagement.UI.Areas.Mvc.ViewModels.Tournaments;
@using VolleyManagement.Domain.RolesAggregate;

@{
    ViewBag.Title = "Schedule";
}

@if (Model == null)
{
    @Html.ValidationMessage("LoadError")
}
else
{
    if (Model.TournamentScheme == TournamentSchemeEnum.PlayOff)
    {
        @Html.Partial("_PlayoffSchedule", Model)
    }
    else
    {
        @Html.Partial("_NonPlayoffSchedule", Model)
    }
}

VolleyManagement.UI/Areas/Mvc/Views/Tournaments/_NonPlayoffSchedule.cshtml
@model VolleyManagement.UI.Areas.Mvc.ViewModels.Tournaments.ScheduleViewModel
@using VolleyManagement.Domain.RolesAggregate;

@Html.HiddenFor(model => model.TournamentId, new { @id = "tournamentId" })
<div style="display:none;">
    @Html.Partial("_SwappedRounds", @Model.MaxNumberOfRounds)
</div>

<h2>
    @Resources.UI.TournamentViews.ScheduleTitle
    @Html.ActionLink(Model.TournamentName, "Details", new { id = Model.TournamentId })
</h2>

@if (Model.MaxNumberOfRounds == 0)
{
    <div class="col-md-6">@Resources.UI.TournamentViews.NoTeamsAvailable</div>
}
else
{
    if (Model.AllowedOperations.IsAllowed(AuthOperations.Games.Create))
    {
        <div>
            @Html.ActionLink(@Resources.UI.TournamentViews.ScheduleGame, "ScheduleGame", new { tournamentId = Model.TournamentId })
        </div>
    }

    <hr>
    <div class="col-md-3">

        @for (byte i = 1; i <= Model.MaxNumberOfRounds; i++)
        {
            <h4>
                @Resources.UI.TournamentViews.Round @i
                @if (Model.AllowedOperations.IsAllowed(AuthOperations.Games.SwapRounds))
                {
                    <button id="swap_round_@i" type="button" class="btn btn-default btn-sm" onclick="SwapRounds(@i)">Swap</button>
                }
            </h4>

            <div class="table-bordered" id="round_@i">
                @if (Model.Rounds.ContainsKey(i))
                {
                    foreach (var game in Model.Rounds[i])
                    {
                        @Html.Partial("_ScheduledGameResult", game);
                    }
                }
                else
                {
                    <div class="row">
                        <div class="col-md-12">@Resources.UI.TournamentViews.NoGamesScheduled</div>
                    </div>
                }
            </div>
        }
    </div>
}

@Html.Hidden("DeleteConfirmationMessage", Resources.UI.GameResultViews.DeleteConfirmationText)
@Scripts.Render("~/bundles/gameresultsscripts")
@Scripts.Render("~/bundles/tournamentroundsscripts")