VolleyManagement.UI/Areas/Mvc/Controllers/NavigationController.cs
namespace VolleyManagement.UI.Areas.Mvc.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using ViewModels.Menu;
    using VolleyManagement.Contracts.Authorization;
    using VolleyManagement.Domain.RolesAggregate;

    /// <summary>
    /// Represents navigation menu controller
    /// </summary>
    public class NavigationController : Controller
    {
        /// <summary>
        /// Holds AuthorizationService instance
        /// </summary>
        private readonly IAuthorizationService _authService;

        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationController"/> class
        /// </summary>
        /// <param name="authService">The authorization service</param>
        public NavigationController(IAuthorizationService authService)
        {
            _authService = authService;
        }

        /// <summary>
        /// Create list of menu items
        /// </summary>
        /// <returns> Partial view of the menu. </returns>
        public PartialViewResult Menu()
        {
            var authorization = _authService.GetAllowedOperations(AuthOperations.Tournaments.ViewArchived);
            string controllerName = (string)Request.RequestContext.RouteData.Values["controller"];
            List<MenuItemViewModel> items = new List<MenuItemViewModel>
                {
                    new MenuItemViewModel() { Name = "Tournaments", Controller = "Tournaments", Action = "Index" },
                    new MenuItemViewModel() { Name = "Players", Controller = "Players", Action = "Index" },
                    new MenuItemViewModel() { Name = "Teams", Controller = "Teams", Action = "Index" },
                    new MenuItemViewModel() { Name = "Contributors", Controller = "ContributorsTeam", Action = "Index" }
                };

            if (authorization.IsAllowed(AuthOperations.Tournaments.ViewArchived))
            {
                items.Add(new MenuItemViewModel() { Name = "Archived tournaments", Controller = "Tournaments", Action = "Archived" });
            }

            var queryableItems = items.AsQueryable();

            var currentItem = queryableItems.Where(item =>
                string.Equals(item.Controller, controllerName, StringComparison.OrdinalIgnoreCase));

            if (currentItem.Count() > 0)
            {
                currentItem.First().IsCurrent = true;
            }

            return PartialView(queryableItems);
        }
    }
}

VolleyManagement.UI/Areas/Mvc/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/commoncss")
    @Styles.Render("~/bundles/admincss")

    @Scripts.Render("~/bundles/commonscripts")
    @Scripts.Render("~/bundles/adminscripts")

    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryvalidation")
    @Scripts.Render("~/bundles/useractionscripts")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>

    <div id="wrapper">
        <!-- Navigation -->
        @Html.Partial("_Navigation")
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        @RenderBody()
                        <hr />
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <footer>
        <p>&copy; Volley Management</p>
    </footer>
</body>
</html>

VolleyManagement.UI/Areas/Mvc/Views/Shared/_MenuLayout.cshtml
@{
    Layout = "~/Areas/Mvc/Views/Shared/_Layout.cshtml";
}

@section Navigation
{
    @{ Html.RenderAction("Menu", "Navigation"); }
}

@RenderBody()

VolleyManagement.UI/Areas/Mvc/Views/Shared/_Navigation.cshtml
@using System.Web.Optimization
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Volley Management", "Index", "Tournaments", null, new { @class = "navbar-brand" })
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            @{ Html.RenderAction("Info", "Account"); }
        </li>
        <li>
            @Html.ActionLink("Feedbacks", "Create", "Feedbacks", null, new { @class = "feedback-link" })
        </li>
    </ul>


    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                @{ Html.RenderAction("Menu", "Navigation"); }
            </ul>
        </div>
    </div>
</nav>